import { invoke } from "@tauri-apps/api/core";
import { TAURI_COMMANDS as C } from "./commands";
import {
  createMockState,
  mockConfigFile,
  mockDatabaseReport,
  mockEnvironmentSnapshot,
  mockFiles,
  mockHealthReport,
  mockHostReport,
  mockLogTail,
  mockProjectInspection,
  mockReleaseInfo,
  mockSitePreview,
  mockSslDiagnostic
} from "../dev/mockState";
import type {
  AppSettings,
  AppSnapshot,
  ArchiveEntry,
  CertificateInfo,
  CmsInstallRequest,
  CmsTemplate,
  CmsUpdateInfo,
  ConfigFile,
  DatabaseInfo,
  DatabaseDiagnosticReport,
  EnvironmentSnapshotInfo,
  FileEntry,
  FileSearchResult,
  HealthReport,
  HostDiagnosticReport,
  HostInfo,
  InstalledTool,
  LogFileTail,
  NodeScript,
  PhpVersion,
  PortInspection,
  ProjectInspection,
  ProjectTool,
  ReleaseInfo,
  ResourceProcess,
  ServiceInfo,
  SitePreview,
  SslDiagnostic,
  TrashRecord
} from "./types";

const isTauriRuntime = () => typeof window !== "undefined" && "__TAURI_INTERNALS__" in window;
const allowBrowserFallback = () => import.meta.env.DEV;

function readFallback<T>(fallback: T | (() => T)): T {
  return typeof fallback === "function" ? (fallback as () => T)() : fallback;
}

async function safeInvoke<T>(command: string, args?: Record<string, unknown>, fallback?: T | (() => T)): Promise<T> {
  if (!isTauriRuntime()) {
    if (fallback !== undefined && allowBrowserFallback()) return readFallback(fallback);
    throw new Error(`Tauri command "${command}" is unavailable in browser preview`);
  }
  return invoke<T>(command, args);
}

export const api = {
  getState: () => safeInvoke<AppSnapshot>(C.getState, undefined, createMockState),
  startAll: () => safeInvoke<AppSnapshot>(C.startAll, undefined, createMockState),
  stopAll: () => safeInvoke<AppSnapshot>(C.stopAll, undefined, createMockState),
  restartAll: () => safeInvoke<AppSnapshot>(C.restartAll, undefined, createMockState),
  startService: (serviceId: string) => safeInvoke<AppSnapshot>(C.startService, { serviceId }, createMockState),
  startServiceProfile: (serviceIds: string[]) => safeInvoke<AppSnapshot>(C.startServiceProfile, { serviceIds }, createMockState),
  stopService: (serviceId: string) => safeInvoke<AppSnapshot>(C.stopService, { serviceId }, createMockState),
  restartService: (serviceId: string) => safeInvoke<AppSnapshot>(C.restartService, { serviceId }, createMockState),
  saveService: (service: ServiceInfo) => safeInvoke<AppSnapshot>(C.saveService, { service }, createMockState),
  installServiceDependency: (serviceId: string) => safeInvoke<AppSnapshot>(C.installServiceDependency, { serviceId }, createMockState),
  updateServiceDependency: (serviceId: string) => safeInvoke<AppSnapshot>(C.updateServiceDependency, { serviceId }, createMockState),
  installAllMissingDependencies: () => safeInvoke<AppSnapshot>(C.installAllMissingDependencies, undefined, createMockState),
  detectDependencies: () => safeInvoke<AppSnapshot>(C.detectDependencies, undefined, createMockState),
  runHealthCheck: () => safeInvoke<HealthReport>(C.runHealthCheck, undefined, mockHealthReport),
  repairEnvironment: () => safeInvoke<HealthReport>(C.repairEnvironment, undefined, () => mockHealthReport("Browser preview repair completed.")),
  saveHost: (host: HostInfo) => safeInvoke<AppSnapshot>(C.saveHost, { host }, createMockState),
  deleteHost: (hostId: string) => safeInvoke<AppSnapshot>(C.deleteHost, { hostId }, createMockState),
  duplicateHost: (hostId: string) => safeInvoke<AppSnapshot>(C.duplicateHost, { hostId }, createMockState),
  syncHostsFile: () => safeInvoke<AppSnapshot>(C.syncHostsFile, undefined, createMockState),
  diagnoseHost: (hostId: string) => safeInvoke<HostDiagnosticReport>(C.diagnoseHost, { hostId }, () => mockHostReport(hostId)),
  repairHost: (hostId: string) => safeInvoke<HostDiagnosticReport>(C.repairHost, { hostId }, () => mockHostReport(hostId)),
  importHosts: (path: string) => safeInvoke<AppSnapshot>(C.importHosts, { path }, createMockState),
  exportHosts: (path: string) => safeInvoke<string>(C.exportHosts, { path }, path),
  savePhpVersion: (php: PhpVersion) => safeInvoke<AppSnapshot>(C.savePhpVersion, { php }, createMockState),
  installPhpVersion: (version: string) => safeInvoke<AppSnapshot>(C.installPhpVersion, { version }, createMockState),
  removePhpVersion: (version: string) => safeInvoke<AppSnapshot>(C.removePhpVersion, { version }, createMockState),
  setDefaultPhp: (version: string) => safeInvoke<AppSnapshot>(C.setDefaultPhp, { version }, createMockState),
  createDatabase: (database: DatabaseInfo) => safeInvoke<AppSnapshot>(C.createDatabase, { database }, createMockState),
  deleteDatabase: (databaseId: string) => safeInvoke<AppSnapshot>(C.deleteDatabase, { databaseId }, createMockState),
  backupDatabase: (databaseId: string) => safeInvoke<string>(C.backupDatabase, { databaseId }, `${databaseId}.sql`),
  importDatabaseSql: (databaseId: string, path = "") => safeInvoke<string>(C.importDatabaseSql, { databaseId, path }, path),
  testDatabaseConnection: (databaseId: string) => safeInvoke<DatabaseDiagnosticReport>(C.testDatabaseConnection, { databaseId }, () => mockDatabaseReport(databaseId)),
  getCmsTemplates: () => safeInvoke<CmsTemplate[]>(C.getCmsTemplates, undefined, () => [
    {
      id: "nextjs",
      name: "Next.js",
      description: "React full-stack application with App Router and local dev server.",
      category: "Node.js",
      downloadUrl: "localstack://node/nextjs",
      documentRoot: ".",
      requiresDatabase: false,
      defaultDatabaseEngine: "MySQL"
    },
    {
      id: "node-express",
      name: "Node.js Express",
      description: "Minimal Express application with local API routes.",
      category: "Node.js",
      downloadUrl: "localstack://node/express",
      documentRoot: ".",
      requiresDatabase: false,
      defaultDatabaseEngine: "MySQL"
    },
    {
      id: "vite-react",
      name: "Vite React",
      description: "Fast React single-page application powered by Vite.",
      category: "Node.js",
      downloadUrl: "localstack://node/vite-react",
      documentRoot: ".",
      requiresDatabase: false,
      defaultDatabaseEngine: "MySQL"
    },
    {
      id: "wordpress",
      name: "WordPress",
      description: "Classic PHP CMS for blogs, shops and company sites.",
      category: "CMS",
      downloadUrl: "https://wordpress.org/latest.zip",
      documentRoot: "public",
      requiresDatabase: true,
      defaultDatabaseEngine: "MySQL"
    }
  ]),
  installCms: (request: CmsInstallRequest) => safeInvoke<AppSnapshot>(C.installCms, { request }, createMockState),
  checkCmsUpdates: () => safeInvoke<CmsUpdateInfo[]>(C.checkCmsUpdates, undefined, []),
  updateCms: (domain: string) => safeInvoke<CmsUpdateInfo>(C.updateCms, { domain }, () => ({ domain, templateId: "", name: domain, currentVersion: "Unknown", latestVersion: "Unknown", updateAvailable: false, canUpdate: false, message: "Browser preview update skipped." })),
  updateAllCms: () => safeInvoke<CmsUpdateInfo[]>(C.updateAllCms, undefined, []),
  generateCertificate: (domain: string, sanDomains: string[]) => safeInvoke<AppSnapshot>(C.generateCertificate, { domain, sanDomains }, createMockState),
  trustCertificate: (certificateId: string) => safeInvoke<AppSnapshot>(C.trustCertificate, { certificateId }, createMockState),
  revokeCertificate: (certificateId: string) => safeInvoke<AppSnapshot>(C.revokeCertificate, { certificateId }, createMockState),
  saveCertificate: (certificate: CertificateInfo) => safeInvoke<AppSnapshot>(C.saveCertificate, { certificate }, createMockState),
  exportCertificate: (certificateId: string, folder: string) => safeInvoke<string>(C.exportCertificate, { certificateId, folder }, `${folder}\\${certificateId}.pem`),
  clearLogs: () => safeInvoke<AppSnapshot>(C.clearLogs, undefined, createMockState),
  exportLogs: (path: string) => safeInvoke<string>(C.exportLogs, { path }, path),
  tailLogFile: (source: string, lines = 200) => safeInvoke<LogFileTail>(C.tailLogFile, { source, lines }, () => mockLogTail(source)),
  saveSettings: (settings: AppSettings) => safeInvoke<AppSnapshot>(C.saveSettings, { settings }, createMockState),
  exportSettings: (path: string) => safeInvoke<string>(C.exportSettings, { path }, path),
  importSettings: (path: string) => safeInvoke<AppSnapshot>(C.importSettings, { path }, createMockState),
  resetSettings: () => safeInvoke<AppSnapshot>(C.resetSettings, undefined, createMockState),
  createAppBackup: (path: string) => safeInvoke<string>(C.createAppBackup, { path }, path),
  restoreAppBackup: (path: string) => safeInvoke<AppSnapshot>(C.restoreAppBackup, { path }, createMockState),
  openCertificateStore: () => safeInvoke<void>(C.openCertificateStore, undefined, () => undefined),
  openDocumentation: () => safeInvoke<void>(C.openDocumentation, undefined, () => undefined),
  openPath: (path: string) => safeInvoke<void>(C.openPath, { path }, () => undefined),
  openUrl: (url: string) => safeInvoke<void>(C.openUrl, { url }, () => undefined),
  openTerminal: (path: string) => safeInvoke<void>(C.openTerminal, { path }, () => undefined),
  openHost: (hostId: string) => safeInvoke<AppSnapshot>(C.openHost, { hostId }, createMockState),
  openDatabaseAdmin: (kind: "phpmyadmin" | "adminer") => safeInvoke<void>(C.openDatabaseAdmin, { kind }, () => undefined),
  scanPorts: () => safeInvoke<PortInspection[]>(C.scanPorts, undefined, []),
  runProjectCommand: (path: string, commandKey: string) => safeInvoke<string>(C.runProjectCommand, { path, commandKey }, "Browser preview command skipped."),
  cloneProjectRepository: (url: string, folder: string) => safeInvoke<string>(C.cloneProjectRepository, { url, folder }, folder),
  inspectProject: (path: string) => safeInvoke<ProjectInspection>(C.inspectProject, { path }, () => mockProjectInspection(path)),
  inspectProjectTools: (path: string) => safeInvoke<ProjectTool[]>(C.inspectProjectTools, { path }, []),
  installProjectTool: (path: string, toolId: string) => safeInvoke<ProjectTool[]>(C.installProjectTool, { path, toolId }, []),
  updateProjectTool: (path: string, toolId: string) => safeInvoke<ProjectTool[]>(C.updateProjectTool, { path, toolId }, []),
  generateEnvTemplate: (path: string, kind: string, database: string, user: string, password: string, domain: string) => safeInvoke<string>(C.generateEnvTemplate, { path, kind, database, user, password, domain }, ""),
  previewHost: (hostId: string) => safeInvoke<SitePreview>(C.previewHost, { hostId }, () => mockSitePreview(hostId)),
  exportPortableHost: (hostId: string, target: string) => safeInvoke<string>(C.exportPortableHost, { hostId, target }, target),
  backupHost: (hostId: string, target: string) => safeInvoke<string>(C.backupHost, { hostId, target }, target),
  restoreHostBackup: (path: string) => safeInvoke<AppSnapshot>(C.restoreHostBackup, { path }, createMockState),
  checkLatestRelease: () => safeInvoke<ReleaseInfo>(C.checkLatestRelease, undefined, mockReleaseInfo),
  downloadLatestReleaseInstaller: () => safeInvoke<string>(C.downloadLatestReleaseInstaller, undefined, ""),
  installDownloadedUpdate: (path: string) => safeInvoke<string>(C.installDownloadedUpdate, { path }, path),
  readConfigFile: (path: string) => safeInvoke<ConfigFile>(C.readConfigFile, { path }, () => mockConfigFile(path)),
  saveConfigFile: (path: string, content: string) => safeInvoke<string>(C.saveConfigFile, { path, content }, path),
  createDiagnosticBundle: (target: string) => safeInvoke<string>(C.createDiagnosticBundle, { target }, target),
  diagnoseSsl: (domain: string) => safeInvoke<SslDiagnostic>(C.diagnoseSsl, { domain }, () => mockSslDiagnostic(domain)),
  inspectInstalledTools: () => safeInvoke<InstalledTool[]>(C.inspectInstalledTools, undefined, []),
  listFiles: (path: string) => safeInvoke<FileEntry[]>(C.listFiles, { path }, () => mockFiles(path)),
  readFile: (path: string) => safeInvoke<ConfigFile>(C.readFile, { path }, () => mockConfigFile(path)),
  readFileWithEncoding: (path: string, encoding: string) => safeInvoke<ConfigFile>(C.readFileWithEncoding, { path, encoding }, () => ({ ...mockConfigFile(path), encoding })),
  writeFile: (path: string, content: string) => safeInvoke<string>(C.writeFile, { path, content }, path),
  writeFileWithEncoding: (path: string, content: string, encoding: string) => safeInvoke<string>(C.writeFileWithEncoding, { path, content, encoding }, path),
  createFile: (path: string) => safeInvoke<string>(C.createFile, { path }, path),
  createFolder: (path: string) => safeInvoke<string>(C.createFolder, { path }, path),
  deletePath: (path: string) => safeInvoke<string>(C.deletePath, { path }, path),
  trashPath: (path: string) => safeInvoke<TrashRecord>(C.trashPath, { path }, { originalPath: path, trashPath: path, name: path.split(/[\\/]/).pop() ?? path, kind: "file" }),
  restoreTrashPath: (originalPath: string, trashPath: string, overwrite: boolean) => safeInvoke<string>(C.restoreTrashPath, { originalPath, trashPath, overwrite }, originalPath),
  renamePath: (path: string, newName: string) => safeInvoke<string>(C.renamePath, { path, newName }, path.replace(/[^\\/]+$/, newName)),
  duplicatePath: (path: string) => safeInvoke<string>(C.duplicatePath, { path }, `${path}.copy`),
  copyPath: (source: string, target: string, overwrite: boolean) => safeInvoke<string>(C.copyPath, { source, target, overwrite }, target),
  movePath: (source: string, target: string, overwrite: boolean) => safeInvoke<string>(C.movePath, { source, target, overwrite }, target),
  chmodPath: (path: string, mode: string, readOnly: boolean) => safeInvoke<string>(C.chmodPath, { path, mode, readOnly }, path),
  uploadFiles: (sources: string[], destination: string, overwrite: boolean) => safeInvoke<string[]>(C.uploadFiles, { sources, destination, overwrite }, () => sources.map((source) => `${destination}\\${source.split(/[\\/]/).pop() ?? "file"}`)),
  extractArchiveTo: (path: string, destination: string) => safeInvoke<string>(C.extractArchiveTo, { path, destination }, destination),
  createArchive: (paths: string[], target: string) => safeInvoke<string>(C.createArchive, { paths, target }, target),
  searchFileContents: (root: string, query: string, regexp: boolean, caseSensitive: boolean) => safeInvoke<FileSearchResult[]>(C.searchFileContents, { root, query, regexp, caseSensitive }, []),
  searchFileContentsAdvanced: (root: string, query: string, regexp: boolean, caseSensitive: boolean, includeExtensions: string, excludeFolders: string, limit: number) => safeInvoke<FileSearchResult[]>(C.searchFileContentsAdvanced, { root, query, regexp, caseSensitive, includeExtensions, excludeFolders, limit }, []),
  listArchiveEntries: (path: string) => safeInvoke<ArchiveEntry[]>(C.listArchiveEntries, { path }, []),
  applyWindowsAcl: (path: string, identity: string, rights: string, inherit: boolean) => safeInvoke<string>(C.applyWindowsAcl, { path, identity, rights, inherit }, path),
  listEnvironmentSnapshots: () => safeInvoke<EnvironmentSnapshotInfo[]>(C.listEnvironmentSnapshots, undefined, []),
  createEnvironmentSnapshot: (name: string) => safeInvoke<EnvironmentSnapshotInfo>(C.createEnvironmentSnapshot, { name }, () => mockEnvironmentSnapshot(name)),
  restoreEnvironmentSnapshot: (id: string) => safeInvoke<AppSnapshot>(C.restoreEnvironmentSnapshot, { id }, createMockState),
  listNodeScripts: (path: string) => safeInvoke<NodeScript[]>(C.listNodeScripts, { path }, []),
  runNodeScript: (path: string, script: string) => safeInvoke<string>(C.runNodeScript, { path, script }, "Browser preview script skipped."),
  resourceMonitor: () => safeInvoke<ResourceProcess[]>(C.resourceMonitor, undefined, []),
  killProcess: (pid: number) => safeInvoke<string>(C.killProcess, { pid }, String(pid)),
  hideTrayPanel: () => safeInvoke<void>(C.hideTrayPanel, undefined, () => undefined),
  openMainPage: (page?: string) => safeInvoke<void>(C.openMainPage, { page }, () => undefined),
  quit: () => safeInvoke<void>(C.quitApp, undefined, () => undefined)
};
